basePath: /tasks
definitions:
  models.Task:
    properties:
      completed:
        type: boolean
      id:
        example: "0"
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Manage Your Tasks
  title: Task Organizator
  version: "1.0"
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Returns the data of all the tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
        "500":
          description: Internal Server Error
      summary: Get a list of all tasks
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: Creates a new task with a unique ID if not provided
      parameters:
      - description: Task object to be created
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
      summary: Create a new task
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: Creates a new task with a unique ID if not provided
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Task object to be created
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
      summary: Create a new task
      tags:
      - Tasks
  /tasks/:
    delete:
      consumes:
      - application/json
      description: Delets All Data
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
      summary: Deletes All Tasks
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a task with the specified ID
      parameters:
      - description: Task ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a task by ID
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Retrieves a task with the specified ID
      parameters:
      - description: Task ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a task by ID
      tags:
      - Tasks
swagger: "2.0"
